version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "download raftt"
          command: |
            curl https://get.raftt.io/install | bash
            raftt init -g $GITHUB_TOKEN
      - run:
          name: "run daemon"
          background: true
          command: |
            raftt daemon-serve
      - run:
          name: "create env"
          command: |
            sleep 5
            raftt up
      - run:
          name: "test"
          command: |
            raftt status
            raftt sh dev -- echo hello

workflows:
  test-workflow:
    jobs:
      - test
